from typing import Any, Callable

def BoolProperty(*args: Any, **kwargs: Any) -> Any: ...
def EnumProperty(*args: Any, **kwargs: Any) -> Any: ...
def FloatProperty(*args: Any, **kwargs: Any) -> Any: ...
def IntProperty(*args: Any, **kwargs: Any) -> Any: ...
def PointerProperty(*args: Any, **kwargs: Any) -> Any: ...
def StringProperty(*args: Any, **kwargs: Any) -> Any: ...

