from typing import Any, Iterable, Sequence

# Minimal mathutils stubs for editor resolution outside Blender.

class Vector:
    def __init__(self, seq: Sequence[float] | None = None) -> None: ...
    length: float
    length_squared: float
    def copy(self) -> "Vector": ...
    def normalized(self) -> "Vector": ...
    def dot(self, other: "Vector") -> float: ...
    def lerp(self, other: "Vector", t: float) -> "Vector": ...

class Matrix:
    @staticmethod
    def Translation(vec: Vector) -> "Matrix": ...
    @staticmethod
    def Identity(size: int = 4) -> "Matrix": ...

